const Txt = {
    'AccountTitle': '帳號管理',
    'CreateAccountBtn': '新增帳號',
    'EditBtn': '編輯',
    'FindNothing': '目前無任何記錄',
    'account': '帳號',
    'password': '密碼',
    'EMail': 'E-mail',
    'status': '狀態',
    'active': '啟用',
    'inactive': '停用',
    'auth': '權限',
    'sure': '確認',
    'cancel': '取消',
    'ReportTitle': '報表管理',
    'ScheduleTitle': '營業時間管理',
    'timeStart': '起',
    'timeEnd': '迄',
    'TimeTagDefaultWord': '選擇狀態',
    'Assign': '指派',
    'TypeDefaultWord': '選擇來源',
    'RecordQueryTitle': '記錄查詢列表',
    'DashboardPieChartTitle': '未結案問題',
    'NotProcessingTitle': '未處理問題',
    'Unfinished': '未結案',
    'RemindMessage': '提醒訊息',
    'PasswordSend': '密碼已寄出',
    'LoginTitle': '登入您的帳號',
    'ForgetPassword': '忘記密碼',
    'Login': '登入',
    'Logout': '登出',
    'Accept': '接受',
    'EditPasswordComplete': '密碼修改成功',
    'Reply': '回覆',
    'EndCaseIconColor': 'primary',  // 已結案的ICON顏色
    'NotEndCaseIconColor': 'error',  // 未結案的ICON顏色
    'OldPasswordPlaceHolder': '請輸入原密碼',
    'NewPasswordPlaceHolder': '請輸入新密碼',
    'CheckPasswordPlaceHolder': '再次請輸入新密碼',
    'Hour': '時',
    'Min': '分',
    'ChooseTime': '時間選擇',
    'SettingError': '設定錯誤！',
    'EndCase': '結案',
    'SheetNumber': '工單號碼',
    'FBId': 'FB ID',
    'SourceType': '訊息來源',
    'category': '訊息分類',
    'keyword': '關鍵字',
    'SystemMessage': '系統訊息',
    'LogoutMessage': '成功登出！',
    'submit': '送出',
    'reset': '重置',
    'back': '返回',
    'notSetting': '未設定欄位資料',
    'ForgetPasswordTitle': '輸入Email，找回密碼',
    'ForgetPasswordBtn': '找回密碼',
    'emailNotFound': 'Email不存在！',
    'option': '選單',
    'search': '搜尋',
    'selectStock': '請選擇股票',
    'BuySellPercentReportTitle': '買賣壓力道比例',
    'StockListTitle': '股票列表',
    'create': '新增',
    'getDataBtn': '取得資料',
    'countDataBtn': '計算資料',

};

export {
    Txt
};